name: Deploy S3 Bucket

on:
  push:
    branches:
    - main

jobs:
  deploy-s3:
    uses: subha7602/GithubActionWorkflows/.github/workflows/terraform-deploy.yml@main
    with:
      aws_region: 'us-east-1'
    secrets:
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
